### ISSUE TITLE
chào mn mình chạy đc rồi nhưng đến bước 3 trích xuất thông tin thì bị lỗi ạ. Ai đó giúp mình với ạ

### ISSUE THREAD

**Issue by manhdoan291** [thelong0705/vietnamese-id-card-ocr#15]
File "/home/doan/Pictures/vietnamese-id-card-ocr/util/util.py", line 87, in runit
    result_info[1] = f(item[0], item[1])
  File "/home/doan/Pictures/vietnamese-id-card-ocr/reader/reader.py", line 22, in get_each_number
    text = pytesseract.image_to_string(img, lang=lang, config=config)
  File "/home/doan/Downloads/yes/lib/python3.8/site-packages/pytesseract/pytesseract.py", line 409, in image_to_string
    return {
  File "/home/doan/Downloads/yes/lib/python3.8/site-packages/pytesseract/pytesseract.py", line 412, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/doan/Downloads/yes/lib/python3.8/site-packages/pytesseract/pytesseract.py", line 287, in run_and_get_output
    run_tesseract(**kwargs)
  File "/home/doan/Downloads/yes/lib/python3.8/site-packages/pytesseract/pytesseract.py", line 263, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, "Failed loading language 'eng' Tesseract couldn't load any languages! Could not initialize tesseract.")
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/home/doan/Downloads/yes/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/doan/Downloads/yes/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/doan/Pictures/vietnamese-id-card-ocr/util/util.py", line 87, in runit
    result_info[1] = f(item[0], item[1])
  File "/home/doan/Pictures/vietnamese-id-card-ocr/reader/reader.py", line 22, in get_each_number
    text = pytesseract.image_to_string(img, lang=lang, config=config)
  File "/home/doan/Downloads/yes/lib/python3.8/site-packages/pytesseract/pytesseract.py", line 409, in image_to_string
    return {
  File "/home/doan/Downloads/yes/lib/python3.8/site-packages/pytesseract/pytesseract.py", line 412, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/doan/Downloads/yes/lib/python3.8/site-packages/pytesseract/pytesseract.py", line 287, in run_and_get_output
    run_tesseract(**kwargs)
  File "/home/doan/Downloads/yes/lib/python3.8/site-packages/pytesseract/pytesseract.py", line 263, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, "Failed loading language 'eng' Tesseract couldn't load any languages! Could not initialize tesseract.")

**Comment by vantuyen-dev** [comment]
Bạn thiếu dict cho Tesseract.

**Comment by thienbui** [comment]
Cài tesseact lên máy bạn nhé. 
`sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel`
`sudo apt install -y tesseract-ocr`
